### ISSUE TITLE
Example not working in the Eq(af) post

### ISSUE THREAD

**Issue by Julow** [dinosaure/blog.x25519.net#1]
The last example of the post contains a typo: https://github.com/dinosaure/blog.x25519.net/blob/092c5a391ad1b9ba5c4e525744cf49252282d816/html/posts/2020-03-14--eqaf-release.org#how-to-fix-it

`idx` is unbound. Fixed with the `for` syntax:

```ocaml
let equal s1 s2 =
  if String.length s1 <> String.length s2 then false
  else
    ( let res = ref true in
      for idx = 0 to String.length s1 - 1
      do res := s1.[idx] = s2.[idx] && !res done ;
      !res )
```

But this function is not branchless, `ocamlopt -g -S` shows that it compiles to:
```ocaml
  ...
    ( let rax = 1 in
      for idx = 0 to String.length s1 - 1
      do
        if s1.[idx] = s2.[idx] then
          rax = 0
      done ;
      rax )
```
The ref `res` is unboxed as `rax` and the `&& !res` part is replaced by a branch.

**Comment by dinosaure** [comment]
Yeah, I decided to avoid so much complexity about the real code into `eqaf` (where we use bitwise operation instead `&&`) to just be understandable for any. Then, thanks for your fix, I wrote the code in the fly :+1:.

**Comment by dinosaure** [comment]
Close by [this commit](https://github.com/dinosaure/blog.x25519.net/commit/741849c013835ed756db9dee9513dfd15e34cd4e).
